### ISSUE TITLE
Error in scatter plot in portfolio report 

### ISSUE THREAD

**Issue by abekhit** [LBNL-JCI-ICF/better#4]
```
Traceback (most recent call last):
  File "run.py", line 13, in <module>
    run_batch(start_id = 1, end_id = 15, saving_target=2, cached_weather=False, batch_report=True)
  File "C:\better\better\demo.py", line 146, in run_batch
    report_portfolio.generate_portfolio_report(report_path)
  File "C:\better\better\report.py", line 806, in generate_portfolio_report
    scatter_html = self.add_2d_scatter_plot(self.portfolio.df_bldg_summary)
  File "C:\better\better\report.py", line 714, in add_2d_scatter_plot
    c_str = v_rgb_str[i]
IndexError: string index out of range

```

**Comment by tsbyq** [comment]
In the old version, the code randomly picks a color for a each location. It went wrong when there are too many locations. Issue no longer exists after removing the color-coding by locations.
